### PR TITLE
Add missing requirements spirv-val to tests

### PR DESCRIPTION
**Pull request by mateuszchudyk**
There is a feature that checks if spirv-val exists, but no test that uses spirv-val requires that it exists.

### CODE REVIEW

**Comment by mateuszchudyk** [comment]
Two actions failed on the test constant-loclist.ll. This PR doesn't touch this file so the problem seems to be on HEAD.

**Comment by svenvh** [comment]
It would be good to hear @MrSidims 's opinion on this too, but I am not keen on making spirv-val a hard requirement for this many tests.  Ideally, if spirv-val is not available, the test would skip validation but should still run the other steps.

**Comment by MrSidims** [comment]
I agree with Sven, we shouldn't skip that many tests.
Btw, I've just make a quick check on my machine with spirv-val non-installed and got the following result:
Total Discovered Tests: 877
  Unsupported      :  **74** (8.44%)
  Passed           : 799 (91.11%)
  Expectedly Failed:   4 (0.46%)
  
I interpret the result like this: there tests that require spirv-as/spirv-dis - and they are skipped. Meanwhile spirv-val tests are still being run as the number of Unsupported tests doesn't match the number of tests modified in this PR. So the question is: why do we need it?

**Comment by mateuszchudyk** [comment]
Makes sense. So basically what we want is that if there's no spirv-val then we want to still run these test and skip just a spirv-val step, right? Now I see that in the [lit.cfg.py:L82](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/main/test/lit.cfg.py#L82) there's a code path which is most likely used to bypass this check. So to sum up I think we can drop this PR.

**Comment by svenvh** [comment]
> the else statement is most likely used to bypass this check (I guess).

Yes exactly, the `else` turns any `spirv-val` into a no-op if spirv-val is not detected.

**Comment by svenvh** [comment]
I think a comment to explain the optionality of spirv-val would be helpful, so I've opened https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2765

**Pull request closed without merging**
