### PR TITLE
Update llvm_release_90 branch with commits from master as of 27.08.2019

### PR DESCRIPTION
**Pull request by aratajew**

### CODE REVIEW

**Comment by aratajew** [comment]
We surely want to get rid of commit 7562f3c from here

**Comment by aratajew** [comment]
Skipped commits:

- 7562f3c

- 2e370df

- be19d39

**Comment by aratajew** [comment]
Also skip commit 507e0f2 - as llvm 80 branch did not switch to C++ 14.

**Comment by aratajew** [comment]
Skip ba902a0 as llvm 80 branch does not contain r369130 change.

**Comment by aratajew** [comment]
Skip 1c6ae9d as clang 90 branch does not contain rL369641.

**Comment by aratajew** [comment]
@svenvh, @AlexeySotkin Do you have any idea why build is failing? 
```
"E: Package 'llvm-9-tools' has no installation candidate
E: Unable to locate package llvm-9-dev
E: Unable to locate package clang-format-9
E: Unable to locate package clang-tidy-9
E: Unable to locate package libclang-9-dev"
```
It looks like some environmental issue and as I'm looking at the change that I'm backporting here it doesn't look like the fail is related to them.

**Comment by AlexeySachkov** [comment]
Hi @aratajew,

Yes, our `.travis.ci.yml` script is a little bit incorrect. We have a PR to fix this: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/318

**Comment by AlexeySachkov** [comment]
@aratajew, could you please re-base your PR? @AlexeySotkin fixed CI build in #323 

I also suggest updating the title, because you are actually merging `master` into `llvm_release_90` and not vice-versa.

**Comment by AlexeySotkin** [comment]
> I also suggest updating the title, because you are actually merging `master` into `llvm_release_90` and not vice-versa.

In the git log it will not look like a *merge* at all.

**Comment by aratajew** [comment]
@svenvh , @AlexeySotkin Guys, could you please take a look?

**Comment by svenvh** [comment]
LGTM mostly, but it would introduce bug https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/331 to the llvm_release_90 release branch.  Perhaps we should wait for #332 and include it in this PR?

**Comment by aratajew** [comment]
> LGTM mostly, but it would introduce bug #331 to the llvm_release_90 release branch. Perhaps we should wait for #332 and include it in this PR?

Right. We should wait for #332.

**Comment by AlexeySotkin** [comment]
@hewj03, #332 has been merged. Could you please add it to this PR ?

**Comment by aratajew** [comment]
> @aratajew, #332 has been merged. Could you please add it to this PR ?

Done.

**Pull request merged**
