### PR TITLE
[OpaquePointers] Convert tests to use -opaque-pointers

### PR DESCRIPTION
**Pull request by jcranmer-intel**
Note that there is one code change in here, to fix the assertion failure for the ndrange test.

### CODE REVIEW

**Comment by jcranmer-intel** [comment]
This also includes the changes from https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2084, because it's easier to see the failure log in that fashion.

**Comment by jcranmer-intel** [comment]
The remaining tests that have -opaque-pointers=0 with this are:
extensions/INTEL/SPV_INTEL_fpga_loop_controls/FPGAIVDepLoopAttrOnClosure.ll
extensions/INTEL/SPV_INTEL_function_pointers/global_ctor_dtor.ll
extensions/INTEL/SPV_INTEL_device_side_avc_motion_esimation/subgroup_avc_intel_types.spt
extensions/INTEL/SPV_INTEL_device_side_avc_motion_esimation/subgroup_avc_intel_types.ll
extensions/INTEL/SPV_INTEL_device_side_avc_motion_esimation/subgroup_avc_intel_wrappers.ll
extensions/INTEL/SPV_INTEL_vector_compute/buffer_surface_intel.ll
extensions/INTEL/SPV_INTEL_vector_compute/decoration_media_block_io.ll
extensions/INTEL/SPV_INTEL_io_pipes/PipeStorageIOINTEL.ll
extensions/INTEL/SPV_INTEL_joint_matrix/sycl_2020_namespace.ll
extensions/INTEL/SPV_INTEL_joint_matrix/joint_matrix_half.ll
extensions/INTEL/SPV_INTEL_joint_matrix/opaque_joint_matrix.ll
extensions/INTEL/SPV_INTEL_joint_matrix/joint_matrix_element.ll
extensions/INTEL/SPV_INTEL_joint_matrix/joint_matrix_bfloat16.ll
extensions/INTEL/SPV_INTEL_joint_matrix/joint_matrix_extract_insert_element_of_sycl_half.ll
extensions/INTEL/SPV_INTEL_joint_matrix/joint_matrix.ll
extensions/INTEL/SPV_INTEL_joint_matrix/joint_matrix_tf32.ll
transcoding/spirv-target-types.ll
transcoding/annotation_dbg_info_drop.ll
transcoding/cl-types.ll
transcoding/spirv-types.ll
transcoding/PipeStorage.ll
transcoding/CreatePipeFromPipeStorage.ll

Of these tests, the remaining status is:
- Several tests rely on checking for opaque structs as their primary or sole test results. Since opaque struct names aren't generated in opaque tests, that means these tests don't do anything.
- annotation_dbg_info_drop.ll is I think handled by @MrSidims 's PR
- PipeStorage seems legitimately broken.
- The first two files in that list should be straightforwardly fixable, but got pushed to the end of my work queue, and I felt it better to push what I had rather than delay this PR further.

**Comment by MrSidims** [comment]
>> annotation_dbg_info_drop.ll is I think handled by @MrSidims 's PR

It XFAILed for now as the test should be completely re-generated since debug info currently attached to bitcasts that are being eliminated.

>> joint matrix

I'll convert the tests

>> Pipe storage

If I'm not mistake initialization through bitcast of pipe storage happens in OpenCL C++ library implementation done by ARM, @svenvh please confirm. Probably this bitcast is broken

**Comment by svenvh** [comment]
> If I'm not mistake initialization through bitcast of pipe storage happens in OpenCL C++ library implementation done by ARM, @svenvh please confirm. Probably this bitcast is broken

The test was added by Intel long ago: https://github.com/KhronosGroup/SPIRV-LLVM/pull/155
It seems to be for OpenCL C++ indeed (as opposed to clang's C++ for OpenCL mode), so I'm not sure how relevant it is these days?

**Review by svenvh — APPROVED** [review]

**Review by MrSidims — APPROVED** [review]

**Pull request merged**
