### PR TITLE
[Backport, llvm12] Backport commits related to SPIRV-Friendly IR generation

### PR DESCRIPTION
**Pull request by aratajew**

### CODE REVIEW

**Comment by MrSidims** [comment]
Shouldn't SPV_KHR_integer_dot_product-nonsat.ll be updated here as well?

**Comment by aratajew** [comment]
> Shouldn't SPV_KHR_integer_dot_product-nonsat.ll be updated here as well?

It looks like the support for SPV_KHR_integer_dot_product extension hasn't been backported to llvm_release_120 branch.

**Comment by aratajew** [comment]
I'll include support for SPV_KHR_integer_dot_product in this PR to preserve consistency between branches.

**Comment by MrSidims** [comment]
> I'll include support for SPV_KHR_integer_dot_product in this PR to preserve consistency between branches.

Ah, I was grepping on llvm_90 and llvm_100 branches and found no support of the extension, while it present in llvm_110, llvm_130 and master branches. While grepping in llvm_120 I incidentally switched to master, so I found the appropriate test and was surprised by the fact, that it's not being modified. I do not insists to cherry-pick the extension here.

**Comment by aratajew** [comment]
> > I'll include support for SPV_KHR_integer_dot_product in this PR to preserve consistency between branches.
> 
> Ah, I was grepping on llvm_90 and llvm_100 branches and found no support of the extension, while it present in llvm_110, llvm_130 and master branches. While grepping in llvm_120 I incidentally switched to master, so I found the appropriate test and was surprised by the fact, that it's not being modified. I do not insists to cherry-pick the extension here.

Ok, so let's have this merged without SPV_KHR_integer_dot_product support.

**Review by MrSidims — APPROVED** [review]

**Pull request merged**
