### PR TITLE
Update LLVM version from 17 to 18

### PR DESCRIPTION
**Pull request by svenvh**
This will not pass out-of-tree checks until the llvm-18 packages are available on apt.llvm.org

We might also want to hold off merging this until all remaining opaque pointer changes are in (to avoid having to cherry-pick them)?

### CODE REVIEW

**Comment by MrSidims** [comment]
Yeah, lets wait until end of week for the merge

**Comment by svenvh** [comment]
Alright, I've created the llvm_release_170 branch now.  We can't merge this PR yet, since the apt packages for llvm-18 aren't there yet.

**Comment by svenvh** [comment]
> We can't merge this PR yet, since the apt packages for llvm-18 aren't there yet.

... although everyone needs the CMakeLists.txt changes to build with llvm's `main`.  @MrSidims any preference if we merge it now, or should we separate out the CMakeLists.txt version bump (or any other ideas)?

**Comment by MrSidims** [comment]
> > We can't merge this PR yet, since the apt packages for llvm-18 aren't there yet.
> 
> ... although everyone needs the CMakeLists.txt changes to build with llvm's `main`. @MrSidims any preference if we merge it now, or should we separate out the CMakeLists.txt version bump (or any other ideas)?

wouldn't https://apt.llvm.org/focal/dists/llvm-toolchain-focal/main/ contain llvm-18 already? My expectation that reverting https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2104 should make CI working

**Comment by svenvh** [comment]
> wouldn't https://apt.llvm.org/focal/dists/llvm-toolchain-focal/main/ contain llvm-18 already? My expectation that reverting https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2104 should make CI working

Ah, I think you may be right.  Let's merge this and revert #2104 then? :-)

**Pull request merged**
