### PR TITLE
Start passing shader type to SPIR-V read function

### PR DESCRIPTION
**Pull request by neildhickey**
This is the first patch from the Arm-Imperial project to extend the translator with Vulkan support.

### CODE REVIEW

**Comment by karolherbst** [comment]
General question: if you want llvm-spirv to accept glsl shader files, why not using glslang to produce SPIR-V instead?

**Comment by karolherbst** [comment]
Or do you want to pass in spirv with different extensions indicating their execution model? The SPIR-V should already contain all the information and we should be able to tell alone from that already. Normally you use those file extensions for the text glsl sources and it might become quite confusing as people would need to start doing things like some_shader.spv.geom or something like that.

**Comment by pierremoreau** [comment]
Agreed with Karol's general question. I thought at first you wanted to still consume OpenCL C/C++ but generate Vulkan SPIR-V instead.

**Comment by neildhickey** [comment]
This project is to extend the SPIR-V translator to accept Vukan SPIR-V and convert to LLVM and vice versa.

**Comment by neildhickey** [comment]
I agree with you though that we should have a single file extension and extract the executionmode from the spirv directly

**Comment by pierremoreau** [comment]
Also, you could end up with the whole pipeline within a single SPIR-V binary (like I like to do), in which case you really need to extract it from the SPIR-V.

**Comment by trenouf** [comment]
(I am an AMD employee.)

It is true that the AMD Vulkan version of the spir-v reader (in the https://github.com/GPUOpen-Drivers/llpc component of the AMDVLK open source driver) also passes the required entry name and execution model into readSpirv(). It then goes on to find that entry point and mark it as dllexport so the rest of the compiler can find it.

It is arguable that that approach (and equally this patch) is wrong. The SPIRVRepresentationInLLVM.rst document quotes a goal of spir-v to be representable in other IRs, especially LLVM. That possibly means that a goal of the spir-v reader is to translate the whole spir-v to llvm IR and then let someone else process the llvm IR itself, including finding entry points.

So, instead (the argument goes), we should represent the name and execution model of each entry point, and then the user of the spir-v reader can use that to find the entry point it wants. Thus this api change to readSpirv() is unnecessary.

As @pierremoreau says, you could put all your pipeline shaders in one spir-v module. What's more, an entry point can have a different name to its function, and two entry points can have the same name as long as their execution models differ.

**Comment by neildhickey** [comment]
Thanks @trenouf I agree, I plan to rework/ abandon the patch to allow all execution models to be parsed in a single file.

**Pull request closed without merging**
