### PR TITLE
Improve lit tests: replace hardcoded parameters with more robust and reliable values

### PR DESCRIPTION
**Pull request by andreytr4intel**

### CODE REVIEW

**Comment by andreytr4intel** [comment]
Recently I've developed a set of scripts (https://github.com/KhronosGroup/SPIRV-LIT-Converter) for converting LIT tests from SPIRV-LLVM-Translator format to LLVM-SPIRV-Backend (https://github.com/KhronosGroup/LLVM-SPIRV-Backend) format. During development and running auto-conversion of lit tests, these scripts help me to find several issues (hardcoded parameters) from original source SPIRV-LLVM-Translator's lit tests, that can be improved, in my opinion, and replaced with more robust and reliable values.
I suggest my fixes to include to original repository. Hope, it would be helpful.

**Comment by andreytr4intel** [comment]
This patch turned out to be quite big, because I have to convert transcoding/OpImageWrite.cl lit test's line endings with dos2unix.
Without NL changes, diff of this file is following:
`
diff --git a/test/transcoding/OpImageWrite.cl b/test/transcoding/OpImageWrite.cl
index 6e77b4f8..59028bad 100644
--- a/test/transcoding/OpImageWrite.cl
+++ b/test/transcoding/OpImageWrite.cl
@@ -7,20 +7,21 @@
 // RUN: llvm-spirv -r %t.spv -o %t.rev.bc --spirv-target-env=SPV-IR
 // RUN: llvm-dis < %t.rev.bc | FileCheck %s --check-prefix=CHECK-SPV-IR

-// CHECK-SPIRV: TypeImage [[IMG2D_WO_TY:[0-9]+]] 2 1 0 0 0 0 0 1
-// CHECK-SPIRV: TypeImage [[IMG2D_RW_TY:[0-9]+]] 2 1 0 0 0 0 0 2
-// CHECK-SPIRV: TypeImage [[IMG2D_ARRAY_WO_TY:[0-9]+]] 2 1 0 1 0 0 0 1
-// CHECK-SPIRV: TypeImage [[IMG2D_ARRAY_RW_TY:[0-9]+]] 2 1 0 1 0 0 0 2
-// CHECK-SPIRV: TypeImage [[IMG1D_WO_TY:[0-9]+]] 2 0 0 0 0 0 0 1
-// CHECK-SPIRV: TypeImage [[IMG1D_RW_TY:[0-9]+]] 2 0 0 0 0 0 0 2
-// CHECK-SPIRV: TypeImage [[IMG1D_BUFFER_WO_TY:[0-9]+]] 2 5 0 0 0 0 0 1
-// CHECK-SPIRV: TypeImage [[IMG1D_BUFFER_RW_TY:[0-9]+]] 2 5 0 0 0 0 0 2
-// CHECK-SPIRV: TypeImage [[IMG1D_ARRAY_WO_TY:[0-9]+]] 2 0 0 1 0 0 0 1
-// CHECK-SPIRV: TypeImage [[IMG1D_ARRAY_RW_TY:[0-9]+]] 2 0 0 1 0 0 0 2
-// CHECK-SPIRV: TypeImage [[IMG2D_DEPTH_WO_TY:[0-9]+]] 2 1 1 0 0 0 0 1
-// CHECK-SPIRV: TypeImage [[IMG2D_ARRAY_DEPTH_WO_TY:[0-9]+]] 2 1 1 1 0 0 0 1
-// CHECK-SPIRV: TypeImage [[IMG3D_WO_TY:[0-9]+]] 2 2 0 0 0 0 0 1
-// CHECK-SPIRV: TypeImage [[IMG3D_RW_TY:[0-9]+]] 2 2 0 0 0 0 0 2
+// CHECK-SPIRV: TypeVoid [[VOID_TY:[0-9]+]]^M
+// CHECK-SPIRV: TypeImage [[IMG2D_WO_TY:[0-9]+]] [[VOID_TY]] 1 0 0 0 0 0 1^M
+// CHECK-SPIRV: TypeImage [[IMG2D_RW_TY:[0-9]+]] [[VOID_TY]] 1 0 0 0 0 0 2^M
+// CHECK-SPIRV: TypeImage [[IMG2D_ARRAY_WO_TY:[0-9]+]] [[VOID_TY]] 1 0 1 0 0 0 1^M
+// CHECK-SPIRV: TypeImage [[IMG2D_ARRAY_RW_TY:[0-9]+]] [[VOID_TY]] 1 0 1 0 0 0 2^M
+// CHECK-SPIRV: TypeImage [[IMG1D_WO_TY:[0-9]+]] [[VOID_TY]] 0 0 0 0 0 0 1^M
+// CHECK-SPIRV: TypeImage [[IMG1D_RW_TY:[0-9]+]] [[VOID_TY]] 0 0 0 0 0 0 2^M
+// CHECK-SPIRV: TypeImage [[IMG1D_BUFFER_WO_TY:[0-9]+]] [[VOID_TY]] 5 0 0 0 0 0 1^M
+// CHECK-SPIRV: TypeImage [[IMG1D_BUFFER_RW_TY:[0-9]+]] [[VOID_TY]] 5 0 0 0 0 0 2^M
+// CHECK-SPIRV: TypeImage [[IMG1D_ARRAY_WO_TY:[0-9]+]] [[VOID_TY]] 0 0 1 0 0 0 1^M
+// CHECK-SPIRV: TypeImage [[IMG1D_ARRAY_RW_TY:[0-9]+]] [[VOID_TY]] 0 0 1 0 0 0 2^M
+// CHECK-SPIRV: TypeImage [[IMG2D_DEPTH_WO_TY:[0-9]+]] [[VOID_TY]] 1 1 0 0 0 0 1^M
+// CHECK-SPIRV: TypeImage [[IMG2D_ARRAY_DEPTH_WO_TY:[0-9]+]] [[VOID_TY]] 1 1 1 0 0 0 1^M
+// CHECK-SPIRV: TypeImage [[IMG3D_WO_TY:[0-9]+]] [[VOID_TY]] 2 0 0 0 0 0 1^M
+// CHECK-SPIRV: TypeImage [[IMG3D_RW_TY:[0-9]+]] [[VOID_TY]] 2 0 0 0 0 0 2^M

 kernel void test_img2d(write_only image2d_t image_wo, read_write image2d_t image_rw)
 {
`

**Comment by andreytr4intel** [comment]
@AlexeySachkov , @MrSidims , @svenvh , @bader , can you, please, take a look at this, or add someone as reviewers?

**Review by bader — APPROVED** [review]

**Comment by bader** [comment]
> This patch turned out to be quite big, because I have to convert transcoding/OpImageWrite.cl lit test's line endings with dos2unix.

Hint: next time make two commits. First commit with just line endings changes, second with meaningful changes.
BTW, GitHub is able to hide whitespace changes and display only meaningful changes.

image

**Comment by andreytr4intel** [comment]
> next time make two commits
OK.

> BTW, GitHub is able to hide whitespace changes and display only meaningful changes.
OK, thanks! Hidden feature. :-)

**Review by MrSidims — APPROVED** [review]
Thanks!

**Comment by andreytr4intel** [comment]
Thanks you too!

**Pull request merged**
