### PR TITLE
Implement read/write_mem_fence

### PR DESCRIPTION
**Pull request by jekstrand**
There's no real difference at the SPIR-V level between these and the
more generic mem_fence intrinsic because mem_fence is already relaxed
and SPIR-V doesn't have a concept of anything more relaxed than that.

Closes: #920

### CODE REVIEW

**Comment by jekstrand** [comment]
I have no idea what your bugfix process is.  I've made the PR against master but this bug exists on all the older versions.  I know this commit cherry-picks cleanly onto 11.0 because that's what I'm working on today.

**Review by svenvh — COMMENTED** [review]
LGTM, but could you add a test?  `test/transcoding/OpenCL/mem_fence.cl` seems like a good place to add the tests to, though the new tests don't have to be as exhaustive as the mem_fence case.

> I've made the PR against master but this bug exists on all the older versions. I know this commit cherry-picks cleanly onto 11.0 because that's what I'm working on today.

That's indeed the work flow, we can cherry-pick this after it lands on `master`.

**Comment by jekstrand** [comment]
> LGTM, but could you add a test?

Sure.  I'll have to figure out how to run them but I'd be happy to add a test case.

**Comment by jekstrand** [comment]
I just updated to add a test.  The test passes but, weirdly, somewhere in the compile pipeline my `read_mem_fence` and `write_mem_fence` intrinsic calls are getting turned into `mem_fence` so the LLVM in the test looks weird.  It only does this with my PR, though, and I have no idea why this PR would cause that.

**Comment by svenvh** [comment]
> I just updated to add a test. The test passes but, weirdly, somewhere in the compile pipeline my `read_mem_fence` and `write_mem_fence` intrinsic calls are getting turned into `mem_fence` so the LLVM in the test looks weird. It only does this with my PR, though, and I have no idea why this PR would cause that.

That is because your PR maps all of `read_mem_fence`, `write_mem_fence`, and `mem_fence` to `OpMemoryBarrier`.  After reaching SPIR-V, there is no way to tell what OpenCL builtin function that `OpMemoryBarrier` originated from.  So when translating back from SPIR-V to LLVM, `visitCallSPIRVMemoryBarrier` will produce a `mem_fence` call.

Given that there is no better SPIR-V mapping for `read_mem_fence` and `write_mem_fence`, this looks like the expected result to me.

**Review by AlexeySachkov — APPROVED** [review]

**Review by svenvh — APPROVED** [review]

**Pull request merged**
