### PR TITLE
[NFC] Use unordered_map for better performance

### PR DESCRIPTION
**Pull request by LU-JOHN**
Use unordered_map instead of map for better performance.

### CODE REVIEW

**Comment by MrSidims** [comment]
I'm expecting, that lots of test would need to be updated, as order of IDs wouldn't remain after it. We would also need to check, if new order of IDs makes sense.
Please also note, that while map to hash table replacement seems legit for {int, int} or {ptr, ptr} pairs, it's less obvious, that it will bring performance benefits for {string, int} pairs.

PS DebugInfo failures are related to https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2357 . You may want to incorporate https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2362 for testing

**Comment by LU-JOHN** [comment]
> I'm expecting, that lots of test would need to be updated, as order of IDs wouldn't remain after it. We would also need to check, if new order of IDs makes sense. Please also note, that while map to hash table replacement seems legit for {int, int} or {ptr, ptr} pairs, it's less obvious, that it will bring performance benefits for {string, int} pairs.
> 
> PS DebugInfo failures are related to #2357 . You may want to incorporate #2362 for testing

I've incorporated #2362.  I think I've avoided changing maps that will affect the output order.

**Comment by LU-JOHN** [comment]
Please take a look @asudarsa @bwlodarcz @MrSidims

**Review by MrSidims — APPROVED** [review]
Tentatively approving, but would be nice to have some numbers for performance improvements.
While in most cases it's LGTM, yet it's less obvious, that it improves std::string key cases.

**Comment by bwlodarcz** [comment]
@MrSidims It's valid improvement on algorithmic level but won't be visible in performance metrics due that other things (getEntry chain) are dominating execution time. Still, the gain is here.

**Review by svenvh — APPROVED** [review]

**Pull request merged**
