### PR TITLE
Fixing issues in type scavenger related to copy efficiency

### PR DESCRIPTION
**Pull request by jgstarIntel**
Eliminating unnecessary copies to improve performance.

### CODE REVIEW

**Comment by MrSidims** [comment]
@vmaksimo @asudarsa @maksimsab @LU-JOHN please take a look

**Review by vmaksimo — COMMENTED** [review]
LGTM, but please fix clang-format

**Review by LU-JOHN — APPROVED** [review]
LGTM

**Review by asudarsa — APPROVED** [review]
LGTM. Thanks

**Comment by asudarsa** [comment]
Adding @jcranmer-intel for review. Thanks

**Review by jcranmer-intel — APPROVED** [review]

**Comment by MrSidims** [comment]
out-of-tree and tidy issues are not related

**Review by MrSidims — APPROVED** [review]

**Pull request merged**
