### PR TITLE
[DbgTran] Fix wrong usage of replaceTemporary

### PR DESCRIPTION
**Pull request by Nuullll**
The uniqued node could have a different address.

Signed-off-by: Yilong Guo <yilong.guo@intel.com>

### CODE REVIEW

**Review by AlexeySotkin — APPROVED** [review]

**Comment by AlexeySotkin** [comment]
@Nuullll could you please add a regression test for the problem you are fixing?

**Comment by Nuullll** [comment]
@AlexeySotkin The reproducer is a little complicated LOL. 
The issue only exists when the same GlobalVariable DebugInfo passes through `SPIRVToLLVMDbgTran::transGlobalVariable` for a second time, **within the same LLVMContext**.

I tried my best to come up with a cpp program as a regression test:
```cpp
// TranslateTwice.cpp
#include "LLVMSPIRVLib.h"

#include "llvm/IR/LLVMContext.h"
#include "llvm/IRReader/IRReader.h"
#include "llvm/Support/CommandLine.h"

#include <iostream>
#include <fstream>

using namespace llvm;

static cl::opt<std::string> InputFile(cl::Positional, cl::desc("<input file>"),
                                      cl::init("-"));

int main(int argc, const char **argv) {

    cl::ParseCommandLineOptions(argc, argv, "Translate twice");

    std::ifstream IS(InputFile, std::ifstream::binary);
    static LLVMContext TheContext;

    Module *M;
    std::string Err;
    readSpirv(TheContext, IS, M, Err);

    IS.clear();
    IS.seekg(0, std::ios::beg);
    readSpirv(TheContext, IS, M, Err);

    return 0;
}
```

And `t.ll`:
```llvm
target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v16:16:16-v24:32:32-v32:32:32-v48:64:64-v64:64:64-v96:128:128-v128:128:128-v192:256:256-v256:256:256-v512:512:512-v1024:1024:1024"
target triple = "spir64-unknown-unknown"

; Function Attrs: nounwind
define spir_kernel void @test() #0 !dbg !21 {
entry:
  ret void, !dbg !24
}

attributes #0 = { nounwind }

!llvm.module.flags = !{!0, !1}
!llvm.dbg.cu = !{!2}
!spirv.MemoryModel = !{!17, !17}
!spirv.Source = !{!18, !19}
!spirv.Generator = !{!20}
!spirv.ExecutionMode = !{}

!0 = !{i32 7, !"Dwarf Version", i32 4}
!1 = !{i32 2, !"Debug Info Version", i32 3}
!2 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !3, producer: "spirv", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !4, imports: !12)
!3 = !DIFile(filename: "1", directory: "/")
!4 = !{!5}
!5 = !DICompositeType(tag: DW_TAG_enumeration_type, name: "_Lock_policy", scope: !6, file: !3, line: 49, baseType: !7, size: 32, flags: DIFlagEnumClass, elements: !8)
!6 = !DINamespace(name: "__gnu_cxx", scope: null)
!7 = !DIBasicType(name: "unsigned int", size: 32, encoding: DW_ATE_unsigned)
!8 = !{!9, !10, !11}
!9 = !DIEnumerator(name: "_S_single", value: 0)
!10 = !DIEnumerator(name: "_S_mutex", value: 1)
!11 = !DIEnumerator(name: "_S_atomic", value: 2)
!12 = !{!13}
!13 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !14, entity: !15, file: !3, line: 90)
!14 = !DINamespace(name: "std", scope: null)
!15 = !DIGlobalVariable(name: "__default_lock_policy", linkageName: "_ZN9__gnu_cxxL21__default_lock_policyE", scope: !6, file: !3, line: 53, type: !16, isLocal: true, isDefinition: false)
!16 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5)
!17 = !{i32 2, i32 2}
!18 = !{i32 4, i32 100000}
!19 = !{i32 3, i32 100000}
!20 = !{i16 6, i16 14}
!21 = distinct !DISubprogram(name: "test", scope: null, file: !3, line: 259, type: !22, flags: DIFlagArtificial | DIFlagPrototyped, spFlags: DISPFlagDefinition | DISPFlagOptimized | DISPFlagMainSubprogram, unit: !2)
!22 = !DISubroutineType(types: !23)
!23 = !{null}
!24 = !DILocation(line: 870, column: 3, scope: !25)
!25 = !DILexicalBlockFile(scope: !21, file: !3, discriminator: 0)

```

And finally, the steps to reproduce:
```bash
g++ TranslateTwice.cpp -o a.out -I./include `llvm-config --cxxflags --ldflags --system-libs --libs Analysis BitWriter Core IRReader Linker Support TransformUtils` -L./build/lib/SPIRV -lLLVMSPIRVLib
llvm-as t.ll && llvm-spirv t.bc && ./a.out t.spv
[1]    10658 segmentation fault (core dumped)  ./a.out t.spv
```

**Do we really want this test in the codebase?**

**Comment by Nuullll** [comment]
ping

**Comment by AlexeySotkin** [comment]
@Nuullll thanks for elaborated test case. No, I don't think we want this test in the codebase.

**Pull request merged**
