### PR TITLE
add support for the 'fcmp false' instruction

### PR DESCRIPTION
**Pull request by VyacheslavLevytskyy**
There is no direct equivalent for "fcmp false" in the specification [https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#_relational_and_logical_instructions], but we may return ConstantFalse in this case instead of reporting error.

This patch depends on https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2216

### CODE REVIEW

**Comment by VyacheslavLevytskyy** [comment]
This patch depends on https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2216. In xmain it would fail without the fixing duplicate type declarations.

**Comment by bwlodarcz** [comment]
Unfortunately the 'fcmp' instruction can go through vector also. I prepared test:
```
define spir_func <4 x i1> @g(<4 x float> %0) {
entry:
 %1 = fcmp false <4 x float> %0, %0
 ret <4 x i1> %1
}
``` 
llvm-as and translator passes but spirv-val
```
error: line 28: OpReturnValue Value <id> '15[%false_0]'s type does not match OpFunction's return type.
  OpReturnValue %false_0
```
Without further investigation I interpret this error that ConstantFalse is constant type declaration. In SPIRV `BoolType != Constant BoolType`. So the return type of the function is not the same as the one returned.

**Comment by VyacheslavLevytskyy** [comment]
@bwlodarcz Thank you. Let's represent a vector of false values as a OpConstantNull ("The null value is type dependent, defined as follows: - Scalar Boolean: false ... Members are set recursively to the null constant according to the null value of their constituent types.")

**Comment by VyacheslavLevytskyy** [comment]
Please take a look @asudarsa @LU-JOHN

**Comment by bwlodarcz** [comment]
LGTM.

**Review by MrSidims — APPROVED** [review]

**Review by asudarsa — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
