### PR TITLE
Enable publishing of built artifacts via github releases.

### PR DESCRIPTION
**Pull request by AlexeySotkin**
This should upload the latest version of the translator to the github repo.

### CODE REVIEW

**Comment by thewilsonator** [comment]
Is anything holding this up? This would be very useful.

**Comment by AlexeySotkin** [comment]
The release archive to be published is over 400MB. It includes the whole build directory. We need to update the patch or travis config.

**Comment by AlexeySotkin** [comment]
I think, ideally, it should be a .deb package. Though, this doesn't mean we can't have zip-packages too.

**Comment by pierremoreau** [comment]
Should it really create a new tag (and release) every time there is a new commit (if I understand properly the changes from this PR)?
Maybe there could be a single release/tag whose artifacts get overwritten every time a new commit is pushed, and separate releases/tags for each actual version of the project.

**Comment by AlexeySotkin** [comment]
You are right. I have fixed that.

**Pull request merged**
