### PR TITLE
Handle llvm.memcpy with non-matching source vs destination alignment.

### PR DESCRIPTION
**Pull request by valerydmit**
Signed-off-by: Valery N Dmitriev <valery.n.dmitriev@intel.com>

### CODE REVIEW

**Comment by dvrogozh** [comment]
Any update on this issue? @valerydmit: do you plan to finalize PR?

**Comment by valerydmit** [comment]
Could somebody having write access to the repository merge this pull request please?

**Comment by dvrogozh** [comment]
> Could somebody having write access to the repository merge this pull request please?

And backport to https://github.com/KhronosGroup/SPIRV-LLVM-Translator/tree/llvm_release_80

**Comment by AlexeySachkov** [comment]
> Could somebody having write access to the repository merge this pull request please?

@svenvh or @AlexeySotkin, could you please merge this PR if you don't have any objections?

**Comment by svenvh** [comment]
Merged to master, I guess we should do a batch backport to llvm_release_80 again.

**Pull request merged**
