### PR TITLE
[DebugInfo] Relax consumer checks for checksum info

### PR DESCRIPTION
**Pull request by MrSidims**
It's a follow up for
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1996 since I couldn't update the PR

### CODE REVIEW

**Comment by MrSidims** [comment]
@vmaksimo @asudarsa @maksimsab @jgstarIntel @LU-JOHN please take a look

**Comment by maksimsab** [comment]
@MrSidims 
Should this change be tested?

**Comment by MrSidims** [comment]
@maksimsab not sure how to do that. It's not a bug fix, it's the comment I had to https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1996 and couldn't apply, because I don't have the appropriate permits in Viktoria's fork.

**Comment by maksimsab** [comment]
Ok, that is alright.

**Review by maksimsab — APPROVED** [review]
LGTM

**Pull request merged**
