### PR TITLE
Improve DbgArrayType compability

### PR DESCRIPTION
**Pull request by KorovinVlad**
This goal is to have compability beteen pre llvm14 and after llvm14 translator versions while translating DbgArrayType. E.g.
llvm_release_100 -> .spv -> llvm_release_140
llvm_release_140 -> .spv -> llvm_release_100

### CODE REVIEW

**Comment by KorovinVlad** [comment]
If(when) this commit will be merged it will be backported to llvm_release_80..llvm_release_90.
For llvm_release_110..llvm_release_130 the following [pr](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1350/files) must be applied.

**Comment by asudarsa** [comment]
Hi @KorovinVlad 

Is it possible to add a test for this?

Thanks

**Comment by MrSidims** [comment]
@vmaksimo please take a look

**Comment by vmaksimo** [comment]
Please disregard comments about `LowerBound`, I see now that it actually exists in those versions. Just to add a test is enough

**Review by asudarsa — APPROVED** [review]
Thanks for adding the test. LGTM.

**Review by vmaksimo — APPROVED** [review]

**Pull request merged**
