### PR TITLE
Report spec constant types when they are queried with --spec-const-info

### PR DESCRIPTION
**Pull request by aarongreig**
Also allow binary float spec constant input by passing a hex value with 0x prefix.

This contribution is being made by Codeplay on behalf of Samsung

### CODE REVIEW

**Comment by MrSidims** [comment]
@aarongreig thanks for your contribution!
It's mandatory for this project to sign CLA to have the patches merged. Please also consider adding a test for the patch.

**Comment by aarongreig** [comment]
Thanks for taking a look at it, I'm waiting for internal confirmation before I sign the CLA but I don't anticipate any problems with it. I've updated the spec constant test to check the new functionality works as expected. I also made a minor reivision to the lit config file as I was having an issue where it used a stale llvm-spirv binary I had lying around in my llvm build directory rather than the one built from this repo, I think this change should be otherwise harmless.

**Comment by aarongreig** [comment]
I don't think it's my changes tripping the CI

**Comment by MrSidims** [comment]
>> I don't think it's my changes tripping the CI

Indeed, I'll close and re-open PR to restart all of the tests, they should be fixed ATM.

**Comment by MrSidims** [comment]
>> I'm waiting for internal confirmation before I sign the CLA

Sure! AFAIK it's not the first Codeplay's contribution to this project, you may ask @Naghasan for examples.

**Review by MrSidims — APPROVED** [review]
The patch looks good, thanks!
I just have may be a silly question, more for my own curiosity, since I'm no so strong with spec constants. Why we use "f16, f32, f64" instead of "half, float, double" (just like in LLVM IR?)

**Review by svenvh — APPROVED** [review]
LGTM.

> Why we use "f16, f32, f64" instead of "half, float, double" (just like in LLVM IR?)

I don't think it's mandated anywhere, so we could pick either. But since we've already used "f<N>" for a while I'd be reluctant to change it.

**Comment by aarongreig** [comment]
I went with the llvm convention kind of out of habit so I'm not particularly attached to it, although it is easier to parse on the other side (e.g. `if(type[0] == 'f') {parseFloatValue()} else if (type[0] == 'i') {parseIntValue()}`)

**Pull request merged**
