### PR TITLE
Refactor switch function creation to generate single return point

### PR DESCRIPTION
**Pull request by delecui**
The refactoring is to simplify the optimization and vectorization of generated functions.

### CODE REVIEW

**Comment by delecui** [comment]
For example, the refactoring will bring below changes to generated function `__translate_spirv_memory_scope`.

### Before
```
define private i32 @__translate_spirv_memory_scope(i32 %key) {
entry:
  switch i32 %key, label %default [
    i32 4, label %case.4
    i32 2, label %case.2
    i32 1, label %case.1
    i32 0, label %case.0
    i32 3, label %case.3
  ]

default:                                          ; preds = %entry
  unreachable

case.4:                                           ; preds = %entry
  ret i32 0

case.2:                                           ; preds = %entry
  ret i32 1

case.1:                                           ; preds = %entry
  ret i32 2

case.0:                                           ; preds = %entry
  ret i32 3

case.3:                                           ; preds = %entry
  ret i32 4
}
```
### After
```
define private i32 @__translate_spirv_memory_scope(i32 %key) {
entry:
  %result = alloca i32, align 4
  switch i32 %key, label %default [
    i32 4, label %case.4
    i32 2, label %case.2
    i32 1, label %case.1
    i32 0, label %case.0
    i32 3, label %case.3
  ]

default:                                          ; preds = %entry
  unreachable

case.4:                                           ; preds = %entry
  store i32 0, ptr %result, align 4
  br label %exit

case.2:                                           ; preds = %entry
  store i32 1, ptr %result, align 4
  br label %exit

case.1:                                           ; preds = %entry
  store i32 2, ptr %result, align 4
  br label %exit

case.0:                                           ; preds = %entry
  store i32 3, ptr %result, align 4
  br label %exit

case.3:                                           ; preds = %entry
  store i32 4, ptr %result, align 4
  br label %exit

exit:                                             ; preds = %case.3, %case.0, %case.1, %case.2, %case.4
  %retVal = load i32, ptr %result, align 4
  ret i32 %retVal
}
```
Generally, the refactoring does not introduce functional changes, but functions with single return point are much easier to optimize or vectorize.

Besides, Clang also generates single return point for functions consisting of switch statement only.
See https://godbolt.org/z/M5cjb88sx

**Comment by delecui** [comment]
@svenvh , @MrSidims, Could you please review the pull request? Thanks.

**Comment by MrSidims** [comment]
Restarting CI

**Comment by MrSidims** [comment]
Restarting CI

**Review by MrSidims — APPROVED** [review]
LGTM

**Review by svenvh — APPROVED** [review]

**Pull request merged**
