### PR TITLE
[NFC] Move Intel extensions tests in separate directory

### PR DESCRIPTION
**Pull request by MrSidims**
There were some tests for extensions placed in test/transcoding.
So for each of these tests was created a separate directory SPV_INTEL_...
and the appropriate tests were moved there.

Also all SPV_INTEL_... dirs were moved into a new one, called
SPV_INTEL_extensions.

Signed-off-by: Dmitry Sidorov <dmitry.sidorov@intel.com>

### CODE REVIEW

**Comment by MrSidims** [comment]
1st part of cleaning tests.
2nd part would be moving tests from base tests dir to transcoding and vice versa.

**Comment by MrSidims** [comment]
@AlexeySotkin @AlexeySachkov @Fznamznon please take a look
@mlychkov FYI

**Comment by MrSidims** [comment]
Also IntelFPGAFunctionAttributes.ll is being moved in a separate PR, see https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1218/files#diff-3fba235acc4a6730a9f42d2ae5eba2965bdd9a46e2275fee2b0bbdeabe7ac724

**Comment by AlexeySotkin** [comment]
I'd suggest creating a structure like in KhronosGroup/SPIRV-Registry repository, i.e. `test/extensions/[EXT|KHR|Company]`

**Comment by MrSidims** [comment]
Closing in favor of another PR

**Pull request closed without merging**
