### PR TITLE
[Backport to 14] Add updated SPV_INTEL_bindless_images preview extension (#2559)

### PR DESCRIPTION
**Pull request by wenju-he**
The updated SPV_INTEL_bindless_images spec can be seen in this PR: intel/llvm#13753

(cherry picked from commit e9a9a3fc1fd3e57449ba22d0065a373eaf4b1a53)

### CODE REVIEW

**Review by MrSidims — APPROVED** [review]
Should https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2576 be incorporated right away?

**Comment by wenju-he** [comment]
> Should #2576 be incorporated right away?

done, thank you @MrSidims for the review.

**Comment by MrSidims** [comment]
@wenju-he please fix LIT tests

**Comment by wenju-he** [comment]
> @wenju-he please fix LIT tests

done. I forgot to amend a local change to the lit.
@MrSidims please take a look again, thank you!

**Pull request merged**
