### PR TITLE
Remove travis CI on llvm_release_120 branch

### PR DESCRIPTION
**Pull request by NikitaRudenkoIntel**

### CODE REVIEW

**Comment by AlexeySotkin** [comment]
@NikitaRudenkoIntel should we close this PR?

**Comment by NikitaRudenkoIntel** [comment]
> should we close this PR?
I created this to check how to fix CI on llvm_release_120 branch.
This can be closed, yes.
Though on this branch we have both github testing and travis. Are both of them necessary?

**Comment by AlexeySotkin** [comment]
> Though on this branch we have both github testing and travis. Are both of them necessary?

This is a good point. I think we can disable Travis CI on this branch already. @AlexeySachkov what do you think?

**Review by svenvh — APPROVED** [review]
Fine with me, assuming we don't need this for releases (@AlexeySotkin you probably know more about that anyway).

**Comment by AlexeySachkov** [comment]
> > Though on this branch we have both github testing and travis. Are both of them necessary?
> 
> This is a good point. I think we can disable Travis CI on this branch already. @AlexeySachkov what do you think?

GitHub Actions CI seems to be stable/reliable enough so we can remove Travis. We indeed don't yet have a way to publish pre-built binaries from GitHub Actions, but that should be technically doable

**Pull request merged**
