### PR TITLE
Restore getArgIndex in OCLTypeToSPIRV

### PR DESCRIPTION
**Pull request by svenvh**
Commit 4a9c78ee ("Prepare SPIRVWriter for type conversion without
opaque pointers. (#1499)", 2022-06-20) removed `getArgIndex` in favor
of passing `Idx`, but this leads to incorrect adaptation of argument
types if sampler arguments are not in the same position between
different functions.

We might be able to drop `adaptArgumentsBySamplerUse` entirely, as we
don't represent samplers as i32 anymore; but for now just fix the
regression.

Fixes https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/1562

### CODE REVIEW

**Comment by svenvh** [comment]
@jcranmer-intel just wondering if the removal of `getArgIndex` was intentional?

**Comment by jcranmer-intel** [comment]
> @jcranmer-intel just wondering if the removal of `getArgIndex` was intentional?

It was. Rather than iterating over the function, it should be possible to just `cast<Argument>(SamplerArg)->getArgNo()` instead.

**Comment by svenvh** [comment]
> It was. Rather than iterating over the function, it should be possible to just cast<Argument>(SamplerArg)->getArgNo() instead.

That's a nice improvement in itself, but that doesn't explain [this change](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1499/files#diff-ce1d0dba5c92bf9cd4c03cef699f218b66153363b26bfdba389a6fb443d2f335L215) in #1499:

```
@@ -206,11 +181,6 @@ void OCLTypeToSPIRVBase::adaptArgumentsBySamplerUse(Module &M) {
[...]
       addWork(Caller);
-      TraceArg(Caller, getArgIndex(Caller, SamplerArg));
+      TraceArg(Caller, Idx);
     }
```

I doubt this is in the way for opaque pointers as we're tracing Values here, but perhaps I'm missing something?

**Comment by jcranmer-intel** [comment]
> I doubt this is in the way for opaque pointers as we're tracing Values here, but perhaps I'm missing something?

It was done as part of the work to convince myself that the if statement that used `getPointerElementType` was unnecessary. Strictly speaking, the change wasn't necessary.

**Review by jcranmer-intel — APPROVED** [review]

**Pull request merged**
