### PR TITLE
[NFCI] Prepare for non-instrinsic debug info

### PR DESCRIPTION
**Pull request by MrSidims**
For now just convert BB with convertFromNewDbgValues, will figure out something smarter a bit later.

I've updated several tests with dbg.declare intrinsic adding --experimental-debuginfo-iterators=1 to check if it works.

Resolved https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2357 for now

### CODE REVIEW

**Comment by MrSidims** [comment]
FYI @jsji

**Review by asudarsa — APPROVED** [review]
Looks good for unblocking our testing. But we will need to handle new debug info. Also, we might need to figure out how to handle this in the reverse translator.
Thanks @MrSidims for a very quick resolution here.

**Comment by MrSidims** [comment]
> But we will need to handle new debug info.

Well, basically we need to remove dbg_decl/var handling by having a case in intrinsic switch and replace it with something. AFAIU there are 2 options:
1. Check associated debug info with alloca's to obtain dbg_decl/var, but it didn't work for me with a single attempt I made there;
2. Smart iteration over basic blocks, as now gdb_decl/var like described here: https://discourse.llvm.org/t/rfc-instruction-api-changes-needed-to-eliminate-debug-intrinsics-from-ir/68939/12 . That is slightly more work, as we would need to rewrite a little bit of code here.

> Also, we might need to figure out how to handle this in the reverse translator.

Nothing to do there.

**Review by svenvh — APPROVED** [review]
LGTM, thanks for working on this!

**Pull request merged**
