### PR TITLE
Fixed some minor errors and typos in lit tests

### PR DESCRIPTION
**Pull request by andreytr4intel**

### CODE REVIEW

**Comment by andreytr4intel** [comment]
Recently I've developed a set of scripts (https://github.com/KhronosGroup/SPIRV-LIT-Converter) for converting LIT tests from SPIRV-LLVM-Translator format to LLVM-SPIRV-Backend (https://github.com/KhronosGroup/LLVM-SPIRV-Backend) format. During developing of these scripts, I've found several issues (typos, errors and other drawbacks) from original source SPIRV-LLVM-Translator's lit tests, that should be corrected, in my opinion.
I suggest my fixes to include to original repository. Hope, it would be useful.

**Comment by andreytr4intel** [comment]
@AlexeySachkov , @MrSidims , @svenvh , @bader , can you, please, take a look at this, or add someone as reviewers?

**Review by bader — APPROVED** [review]

**Review by MrSidims — APPROVED** [review]

**Comment by andreytr4intel** [comment]
Thanks!

**Comment by andreytr4intel** [comment]
@bader , @MrSidims , @AlexeySachkov , 
FYI:
I've also found following "errors", but I suppose, its intentional, because if I fix its, tests start to fail.
```
diff --git a/test/transcoding/builtin_vars_arithmetics.ll b/test/transcoding/builtin_vars_arithmetics.ll
index 4ecbbb49..a7db3db9 100644
--- a/test/transcoding/builtin_vars_arithmetics.ll
+++ b/test/transcoding/builtin_vars_arithmetics.ll
@@ -71,8 +71,8 @@
 ; CHECK-LLVM-OCL:  %[[GOffset2:[0-9]+]] = call spir_func i64 @_Z17get_global_offsetj(i32 2) #1
 ; CHECK-LLVM-SPV:  %[[GOffset2:[0-9]+]] = call spir_func i64 @_Z25__spirv_BuiltInGlobalSizei(i32 2) #1
 ; CHECK-LLVM:  %[[GOffsetVec:[0-9]+]] = insertelement <3 x i64> %[[SecondVec2]], i64 %[[GOffset2]], i32 2
-; CHECK-LLVM  %20 = sub <3 x i64> %[[GlobSizeVec]], %[[GOffsetVec]]
-; CHECK-LLVM  %21 = sub <3 x i64> %[[GlobSizeVec]], %[[GOffSetVec]]
+; CHECK-LLVM:  %20 = sub <3 x i64> %[[GlobSizeVec]], %[[GOffsetVec]]
+; CHECK-LLVM:  %21 = sub <3 x i64> %[[GlobSizeVec]], %[[GOffSetVec]]

 target datalayout = "e-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-n8:16:32:64"
 target triple = "spir64-unknown-linux"
diff --git a/test/transcoding/intel_usm_addrspaces.ll b/test/transcoding/intel_usm_addrspaces.ll
index aa90e8dd..849c9896 100644
--- a/test/transcoding/intel_usm_addrspaces.ll
+++ b/test/transcoding/intel_usm_addrspaces.ll
@@ -127,7 +127,7 @@ entry:
 ; CHECK-SPIRV: Load {{[0-9]+}} [[CAST_FROM1:[0-9]+]] [[GLOB_ARG1]] {{[0-9]+}} {{[0-9]+}}
 ; CHECK-SPIRV-EXT: CrossWorkgroupCastToPtrINTEL {{[0-9]+}} [[CAST_TO1:[0-9]+]] [[CAST_FROM1]]
 ; CHECK-SPIRV-NO-EXT-NOT: GenericCastToPtr {{[0-9]+}} [[CAST_TO1:[0-9]+]] [[CAST_FROM1]]
-; CHECL-SPIRV: Store [[DEVICE_ARG1]] [[CAST_TO1]] {{[0-9]+}} {{[0-9]+}}
+; CHECK-SPIRV: Store [[DEVICE_ARG1]] [[CAST_TO1]] {{[0-9]+}} {{[0-9]+}}
 ; Function Attrs: norecurse nounwind
 define spir_func void @_Z3booPii(i32 addrspace(1)* %arg_glob, i32 addrspace(5)* %arg_dev) #3 !kernel_arg_addr_space !9 {
 entry:
@@ -146,7 +146,7 @@ entry:
 ; CHECK-SPIRV: Load {{[0-9]+}} [[CAST_FROM2:[0-9]+]] [[GLOB_ARG2]] {{[0-9]+}} {{[0-9]+}}
 ; CHECK-SPIRV-EXT: CrossWorkgroupCastToPtrINTEL {{[0-9]+}} [[CAST_TO2:[0-9]+]] [[CAST_FROM2]]
 ; CHECK-SPIRV-NO-EXT-NOT: GenericCastToPtr {{[0-9]+}} [[CAST_TO2:[0-9]+]] [[CAST_FROM2]]
-; CHECL-SPIRV: Store [[HOST_ARG1]] [[CAST_TO2]] {{[0-9]+}} {{[0-9]+}}
+; CHECK-SPIRV: Store [[HOST_ARG1]] [[CAST_TO2]] {{[0-9]+}} {{[0-9]+}}
 ; Function Attrs: norecurse nounwind
 define spir_func void @_Z3gooPii(i32 addrspace(1)* %arg_glob, i32 addrspace(6)* %arg_host) #3 !kernel_arg_addr_space !10 {
 entry:
@@ -165,7 +165,7 @@ entry:
 ; CHECK-SPIRV: Load {{[0-9]+}} [[CAST_FROM3:[0-9]+]] [[DEVICE_ARG2]] {{[0-9]+}} {{[0-9]+}}
 ; CHECK-SPIRV-EXT: PtrCastToCrossWorkgroupINTEL {{[0-9]+}} [[CAST_TO3:[0-9]+]] [[CAST_FROM3]]
 ; CHECK-SPIRV-NO-EXT-NOT: PtrCastToGeneric {{[0-9]+}} [[CAST_TO3:[0-9]+]] [[CAST_FROM3]]
-; CHECL-SPIRV: Store [[GLOB_ARG3]] [[CAST_TO3]] {{[0-9]+}} {{[0-9]+}}
+; CHECK-SPIRV: Store [[GLOB_ARG3]] [[CAST_TO3]] {{[0-9]+}} {{[0-9]+}}
 ; Function Attrs: norecurse nounwind
 define spir_func void @_Z3zooPii(i32 addrspace(1)* %arg_glob, i32 addrspace(5)* %arg_dev) #3 !kernel_arg_addr_space !9 {
 entry:
@@ -184,7 +184,7 @@ entry:
 ; CHECK-SPIRV: Load {{[0-9]+}} [[CAST_FROM4:[0-9]+]] [[HOST_ARG2]] {{[0-9]+}} {{[0-9]+}}
 ; CHECK-SPIRV-EXT: PtrCastToCrossWorkgroupINTEL {{[0-9]+}} [[CAST_TO4:[0-9]+]] [[CAST_FROM4]]
 ; CHECK-SPIRV-NO-EXT-NOT: PtrCastToGeneric {{[0-9]+}} [[CAST_TO4:[0-9]+]] [[CAST_FROM4]]
-; CHECL-SPIRV: Store [[GLOB_ARG4]] [[CAST_TO4]] {{[0-9]+}} {{[0-9]+}}
+; CHECK-SPIRV: Store [[GLOB_ARG4]] [[CAST_TO4]] {{[0-9]+}} {{[0-9]+}}
 ; Function Attrs: norecurse nounwind
 define spir_func void @_Z3mooPii(i32 addrspace(1)* %arg_glob, i32 addrspace(6)* %arg_host) #3 !kernel_arg_addr_space !10 {
 entry:
```
I think, these tests are unfinished, so I didn't include these fixes to this patch. But I think, it would be worth to mention it.

**Comment by bader** [comment]
I think these are just typos and we better fix them.

**Comment by andreytr4intel** [comment]
If fix only typos, then FileCheck can't find some of variables referenced in parameters of CHECK directives, so something should be added too.
I think, it should be understood, what authors ( @AlexeySachkov and @MrSidims ) meant, or ask them to take a look at this.

**Pull request merged**
