### PR TITLE
Update DebugInfo tests for op-index addition

### PR DESCRIPTION
**Pull request by svenvh**
Update tests for llvm-project commit 6aa94c64a532 ("[DWARF] Add printout for op-index", 2023-07-12).

### CODE REVIEW

**Comment by svenvh** [comment]
There are more test failures which I suspect are due to an opaque-pointers change.

**Comment by MrSidims** [comment]
>> Update tests for llvm-project commit 6aa94c64a532 ("[DWARF] Add printout for op-index", 2023-07-12).

I'm also got some notification, though haven't yet updated my local ws. But from notifications I got a feeling, that in-tree tests for debug info are passing, while out-of-tree tests are failing. So was the patch reverted/relanded?

**Comment by svenvh** [comment]
> > > Update tests for llvm-project commit 6aa94c64a532 ("[DWARF] Add printout for op-index", 2023-07-12).
> 
> I'm also got some notification, though haven't yet updated my local ws. But from notifications I got a feeling, that in-tree tests for debug info are passing, while out-of-tree tests are failing. So was the patch reverted/relanded?

In-tree doesn't run the debug info tests, as we don't have enough CPU time to build all the tools required for running those tests.

**Comment by MrSidims** [comment]
> In-tree doesn't run the debug info tests, as we don't have enough CPU time to build all the tools required for running those tests.

Wow, I didn't know.

I can take care of GEP / annotations / opaque pointers related failures.

**Review by MrSidims — APPROVED** [review]

**Comment by svenvh** [comment]
> I can take care of GEP / annotations / opaque pointers related failures.

That would be great, thanks!

**Pull request merged**
