### PR TITLE
Update LLVM version 9 -> 10

### PR DESCRIPTION
**Pull request by svenvh**

### CODE REVIEW

**Comment by AlexeySachkov** [comment]
@svenvh, @AlexeySotkin, FYI: https://bugs.llvm.org/show_bug.cgi?id=42593
http://lists.llvm.org/pipermail/cfe-dev/2019-August/063112.html

**Comment by svenvh** [comment]
The 18.04 (Bionic) binaries seem to be up to date again, let's see if we can build against latest llvm master again when we move our Travis config from 16.04 to 18.04.  Would there be any objections against doing so?

**Comment by StuartDBrady** [comment]
LGTM.

@AlexeySachkov, this removes the `pyenv global 3.7` line. Do you know if it's still needed?

**Comment by AlexeySachkov** [comment]
> @AlexeySachkov, this removes the pyenv global 3.7 line. Do you know if it's still needed?

I don't know exactly, but if everything is working without this `pyenv` stuff, then probably it is not needed anymore.

@svenvh, I have no objections regarding moving to Ubuntu 18.04

**Comment by svenvh** [comment]
> LGTM.
> 
> @AlexeySachkov, this removes the `pyenv global 3.7` line. Do you know if it's still needed?

I removed it as it was causing problems on 18.04:

```
$ pyenv global 3.7
pyenv: version `3.7' not installed
The command "pyenv global 3.7
" exited with 1.```

I tried `3.6` which failed too, but it seems we actually no longer need it.

**Comment by svenvh** [comment]
> @svenvh, I have no objections regarding moving to Ubuntu 18.04

Thanks!  I'll wait to see if @AlexeySotkin is happy moving to 18.04 too before merging.

If desired we can switch back to 16.04 when the Xenial llvm binaries are up to date again.

**Comment by AlexeySachkov** [comment]
> Thanks! I'll wait to see if @AlexeySotkin is happy moving to 18.04 too before merging.

I'm afraid that @AlexeySotkin will not be able to comment here in the next two weeks. So, it is probably better to proceed without waiting for him. 

@bader, do you have an opinion here?

**Comment by bader** [comment]
I'm okay with moving to regular testing 18.04.
We can enable testing with 16.04 on release branches if there is interest in supporting old Ubuntu version(s). Right?

**Comment by svenvh** [comment]
> I'm okay with moving to regular testing 18.04.

Thanks, I'll merge this PR then.

> We can enable testing with 16.04 on release branches if there is interest in supporting old Ubuntu version(s). Right?

I'm only moving the master branch testing to 18.04 (possibly temporarily).  I think we can keep the release branches on 16.04 for now, as for older llvm versions there are no problems with the 16.04 llvm packages.

**Pull request merged**
