### PR TITLE
Making LIT tests passing on Windows

### PR DESCRIPTION
**Pull request by AlexeySotkin**

### CODE REVIEW

**Comment by AlexeySachkov** [comment]
@AlexeySotkin, don't you think that we need CI on Windows (#105) to check such patches? :)

**Comment by AlexeySotkin** [comment]
I do think so :) I'm going to add it to travis a little bit later.

**Comment by tremmelg** [comment]
The tests that use `spirv-val` will currently fail on Windows when `spirv-val` is not found, as `:` is not a valid command (https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/master/test/lit.cfg.py#L61)

**Comment by vladimirlaz** [comment]
> The tests that use `spirv-val` will currently fail on Windows when `spirv-val` is not found, as `:` is not a valid command (https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/master/test/lit.cfg.py#L61)

can we just replace `:` with `echo`. It should work both on Windows and Linux.

**Comment by tremmelg** [comment]
> > The tests that use `spirv-val` will currently fail on Windows when `spirv-val` is not found, as `:` is not a valid command (https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/master/test/lit.cfg.py#L61)
> 
> can we just replace `:` with `echo`. It should work both on Windows and Linux.

Yeah, that would. work

**Comment by vladimirlaz** [comment]
Do we have any chance to submit this PR? It passed testing and has approval.

**Pull request merged**
