### PR TITLE
Remove deprecated spirv-atomic-prefix option

### PR DESCRIPTION
**Pull request by aratajew**
For details about motivation of removing this code check: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/514

### CODE REVIEW

**Comment by aratajew** [comment]
@svenvh could we please merge it? Also for the other branches.

**Comment by svenvh** [comment]
> @svenvh could we please merge it? Also for the other branches.

I was waiting for @AlexeySachkov and @AlexeySotkin to confirm they are happy with the removal too (perhaps I should have tagged them).

**Comment by bader** [comment]
Sorry, for the delay, guys. Russia is on public holidays. I hope Alexey's will be able to review tomorrow.

**Comment by AlexeySachkov** [comment]
We are mostly using the translator via library interface and since this option is not available there - we couldn't rely on it and this PR should make no difference for us.

intel/llvm project is using the translator as binary, but we don't use this option in there.

@AlexeySotkin, please also confirm that removal is safe for us

**Pull request merged**
