### PR TITLE
Update gen_spirv.bash

### PR DESCRIPTION
**Pull request by svenvh**
Update `gen_spirv.bash` to align it with the current code base.  This PR does not synchronize the generated files with the script output yet; I plan to do that in a followup pull request including a cleanup of generated functions that are not used. By keeping that separate, the changes should be easier to review.

This PR includes:
- Special-case builtins in gen_spirv.bash
- Do not generate NameMap or isValid for SPIR-V ops
- Align gen_spirv.bash with current formatting
- Derive output file name from type argument
- Remove td file generation from gen_spirv.bash

### CODE REVIEW

**Comment by AlexeySotkin** [comment]
@svenvh, could you please provide example of the script output?

**Comment by svenvh** [comment]
> @svenvh, could you please provide example of the script output?

The full output is the entire `lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h` file when invoked as `bash tools/spirv-tool/gen_spirv.bash lib/SPIRV/libSPIRV/spirv.hpp NameMap`, but then updated for recent additions to `spirv.hpp`. It's too big to paste it here, but to give you an idea, after invoking it, it will rewrite `lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h` such that the diff looks like:

```
diff --git a/lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h b/lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
index a1a1d19..b6f2d60 100644
--- a/lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
+++ b/lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
@@ -59,6 +59,8 @@ template <> inline void SPIRVMap<SourceLanguage, std::string>::init() {
   add(SourceLanguageGLSL, "GLSL");
   add(SourceLanguageOpenCL_C, "OpenCL_C");
   add(SourceLanguageOpenCL_CPP, "OpenCL_CPP");
+  add(SourceLanguageHLSL, "HLSL");
+  add(SourceLanguageMax, "Max");
 }
 SPIRV_DEF_NAMEMAP(SourceLanguage, SPIRVSourceLanguageNameMap)
 
@@ -70,6 +72,15 @@ template <> inline void SPIRVMap<ExecutionModel, std::string>::init() {
   add(ExecutionModelFragment, "Fragment");
   add(ExecutionModelGLCompute, "GLCompute");
   add(ExecutionModelKernel, "Kernel");
+  add(ExecutionModelTaskNV, "TaskNV");
+  add(ExecutionModelMeshNV, "MeshNV");

... etc ...
```

Similarly, here is the start of a diff after invoking the script to generate the isValid functions: `bash tools/spirv-tool/gen_spirv.bash lib/SPIRV/libSPIRV/spirv.hpp isValid`:
```
diff --git a/lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h b/lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
index 76a7e81..c9d822e 100644
--- a/lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
+++ b/lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
@@ -60,6 +60,8 @@ inline bool isValid(spv::SourceLanguage V) {
   case SourceLanguageGLSL:
   case SourceLanguageOpenCL_C:
   case SourceLanguageOpenCL_CPP:
+  case SourceLanguageHLSL:
+  case SourceLanguageMax:
     return true;
   default:
     return false;

... etc ...
```

**Comment by AlexeySotkin** [comment]
What is supposed usage model for this script?

**Comment by AlexeySachkov** [comment]
> What is supposed usage model for this script? I know that the script is here for quite a long time, but I've never used it :-)

If I understand correctly, the correct way of updating out copy of `spirv.hpp` is launching this script instead of manual changes of the file.

@svenvh, am I right that this PR is a step towards resolving #210? I guess it should be launched regularly (or even during build time) to generate `spirv.hpp` from `.json` files

**Comment by svenvh** [comment]
> What is supposed usage model for this script? I know that the script is here for quite a long time, but I've never used it :-)

This script is supposed to be used to generate `lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h` and `lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h`, as can be seen from a comment in those files:

```
// WARNING:
//
// This file has been generated using `tools/spirv-tool/gen_spirv.bash` and
// should not be modified manually. If the file needs to be updated, edit the
// script and any other source file instead, before re-generating this file.
```

So the intended usage is when spirv.hpp is updated, this script is run to generate the aforementioned SPIRV*Enum.h files.  No one has been doing that for a while (I didn't know about this script either), so the header files and the script are out of sync at the moment.  This PR brings them closer together, but doesn't update the header files yet.  The reason for not bringing them in sync is this PR is that I want to cleanup the generated code to reduce llvm-spirv build times a bit, and syncing them now would only add more unused code (so I want to do the sync and the cleanup in the next PR, which should also make it easier to review).

> the correct way of updating out copy of spirv.hpp is launching this script instead of manual changes of the file.

Almost, this script should be run *after* updating spirv.hpp.

> @svenvh, am I right that this PR is a step towards resolving #210? I guess that the script should be launched regularly (or even during build time) to generate spirv.hpp from .json files

It won't really solve #210, but longer term we should perhaps make it part of the build system. Such that llvm-spirv's header files are regenerated whenever spirv.hpp is modified.

**Comment by svenvh** [comment]
(had to rebase due to a merge conflict)

**Pull request merged**
