### PR TITLE
[Backport][120] Add support for cl_ext_float_atomics

### PR DESCRIPTION
**Pull request by haonanya**
This patch backports https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/916,
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/939 and
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1116 from master to
llvm_release_120.
Note: There are gaps on some data structures, for example there are SPIRVToOCL12
and SPIRVToOCL20 class for llvm_release_120 while SPIRVToOCL12Base and
SPIRVToOCL20Base for master, but they should play same role on the branch where
they are.

Signed-off-by: haonanya <haonan.yang@intel.com>

### CODE REVIEW

**Comment by AlexeySotkin** [comment]
@haonanya Why do we need #939 here?

**Comment by AlexeySotkin** [comment]
@AGindinson could you please take a look.

**Comment by haonanya** [comment]
> @haonanya Why do we need #939 here?
It should support bi-directional translation for cl_ext_float_atomics extension, and #939 is SPIRV Reader translation part.

**Review by AGindinson — APPROVED** [review]
LGTM.

**Review by AlexeySotkin — APPROVED** [review]

**Pull request merged**
