### PR TITLE
[NFC] Re-organize tests a bit

### PR DESCRIPTION
**Pull request by AlexeySachkov**
Renamed tests for LLVM intrinsics from "something" to "llvm.something" to better represent their idea tot test particular llvm intrinsic.
Moved negative tests into corresponding folder

### CODE REVIEW

**Comment by svenvh** [comment]
You can probably take `-negative` out of the `spirv-version-controls-` test names.

Otherwise LGTM, thanks!

**Comment by AlexeySotkin** [comment]
I think it makes sense to organize/move tests for llvm intrinsics into a separate new directory named like `llvm-intrinsics`.

**Comment by AlexeySachkov** [comment]
> You can probably take `-negative` out of the `spirv-version-controls-` test names.

Done in e649c0c83e3b163b1793389da4aa2e3afdd96463

**Comment by AlexeySachkov** [comment]
> I think it makes sense to organize/move tests for llvm intrinsics into a separate new directory named like `llvm-intrinsics`.

Done in 732ea11b0ea5fec912d8d0b161b5cec7e407d666

**Comment by svenvh** [comment]
Not sure if all of the renaming you did was intentional, but it seems part of the intrinsic names went missing. For example:

```
test/transcoding/llvm.memcpy.align.ll → test/llvm-intrinsics/align.ll
test/llvm.sadd.with.overflow.ll → test/llvm-intrinsics/overflow.ll
test/usub-sat.ll → test/llvm-intrinsics/sat.ll```

**Comment by AlexeySachkov** [comment]
> Not sure if all of the renaming you did was intentional, but it seems part of the intrinsic names went missing. For example:
> 
> ```
> test/transcoding/llvm.memcpy.align.ll → test/llvm-intrinsics/align.ll
> test/llvm.sadd.with.overflow.ll → test/llvm-intrinsics/overflow.ll
> test/usub-sat.ll → test/llvm-intrinsics/sat.ll```
> ```

Thanks for the catch! This wasn't intentional: I just used some bash scripting to automatically rename files and it turned out to work in a bit different driver. Fixed in 04835309e424a532824e2d397bdcaa3712730f8c

**Review by svenvh — APPROVED** [review]
LGTM!

**Pull request merged**
