### PR TITLE
Fix various compiler errors.

### PR DESCRIPTION
**Pull request by zahiraam**
Our compiler is triggering various errors. This is a patch to fix them.

### CODE REVIEW

**Review by AlexeySachkov — APPROVED** [review]

**Comment by zahiraam** [comment]
Not sure why those test files showed up in my PR? I will revert them.

**Comment by svenvh** [comment]
This PR looks a bit weird as you seem to be merging older commits too?  Please try rebasing onto the latest `master` branch of this repository and then force push to your `build-errors` branch.

**Comment by zahiraam** [comment]
> This PR looks a bit weird as you seem to be merging older commits too? Please try rebasing onto the latest `master` branch of this repository and then force push to your `build-errors` branch.

Rebased. Thanks.

**Comment by zahiraam** [comment]
Review please! Thanks.

**Comment by AlexeySachkov** [comment]
@zahiraam, I'm ok with the changes, but something is still wrong with the PR:

> This branch cannot be rebased due to conflicts
> Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch.

**Comment by AlexeySachkov** [comment]
@zahiraam, I've cleaned up your branch, will merge the PR once CI finishes its execution if there are no objections from others

**Comment by zahiraam** [comment]
> @zahiraam, I've cleaned up your branch, will merge the PR once CI finishes its execution if there are no objections from others

Thanks.

**Review by AlexeySotkin — APPROVED** [review]

**Pull request merged**
