### PR TITLE
Fix crash on debug info when -spirv-allow-unknow-intrinsics option enabled

### PR DESCRIPTION
**Pull request by NikitaRudenkoIntel**
Bug is caused by translating of known intrinsics declarations, which should not be translated.

### CODE REVIEW

**Comment by Hopetech** [comment]
Duplicate from #609  ?

**Comment by NikitaRudenkoIntel** [comment]
No, it is for another branch

**Comment by Hopetech** [comment]
Oh my bad

**Comment by AlexeySotkin** [comment]
Please fix clang-format https://travis-ci.org/github/KhronosGroup/SPIRV-LLVM-Translator/jobs/706129500#L592 and squash your commits.
Other than that LGTM. Thanks!

**Pull request merged**
